const POMODORO = 'POMODORO';
const SHORT_BREAK = 'SHORT_BREAK';
const LONG_BREAK = 'LONG_BREAK';
const START = 'START';
const STOP = 'STOP';
const RESET = 'RESET';
const UPDATE_FINISHED = 'UPDATED_FINISHED';
const RESET_FINISHED = 'RESET_FINISHED';

export {
  POMODORO,
  SHORT_BREAK,
  LONG_BREAK,
  START,
  STOP,
  RESET,
  UPDATE_FINISHED,
  RESET_FINISHED
};
